interface Boxer {
	id: string
	name: string
	age: number
	weight: number
	height: number
	country: string
	realName?: string
}

export const BOXERS_LEFT: Boxer[] = [
	{
		id: "el-mariana",
		name: "El Mariana",
		realName: "Osvaldo Palacios Flores",
		age: 25,
		weight: 87,
		height: 1.95,
		country: "mx",
	},
	{
		id: "el-mariana",
		name: "El Mariana",
		realName: "Osvaldo Palacios Flores",
		age: 25,
		weight: 87,
		height: 1.95,
		country: "mx",
	},
	{
		id: "el-mariana",
		name: "El Mariana",
		realName: "Osvaldo Palacios Flores",
		age: 25,
		weight: 87,
		height: 1.95,
		country: "mx",
	},
	{
		id: "el-mariana",
		name: "El Mariana",
		realName: "Osvaldo Palacios Flores",
		age: 25,
		weight: 87,
		height: 1.95,
		country: "mx",
	},
	{
		id: "el-mariana",
		name: "El Mariana",
		realName: "Osvaldo Palacios Flores",
		age: 25,
		weight: 87,
		height: 1.95,
		country: "mx",
	},
	{
		id: "el-mariana",
		name: "El Mariana",
		realName: "Osvaldo Palacios Flores",
		age: 25,
		weight: 87,
		height: 1.95,
		country: "mx",
	},
	{
		id: "el-mariana",
		name: "El Mariana",
		realName: "Osvaldo Palacios Flores",
		age: 25,
		weight: 87,
		height: 1.95,
		country: "mx",
	},
	{
		id: "el-mariana",
		name: "El Mariana",
		realName: "Osvaldo Palacios Flores",
		age: 25,
		weight: 87,
		height: 1.95,
		country: "mx",
	},
	{
		id: "el-mariana",
		name: "El Mariana",
		realName: "Osvaldo Palacios Flores",
		age: 25,
		weight: 87,
		height: 1.95,
		country: "mx",
	},
	{
		id: "el-mariana",
		name: "El Mariana",
		realName: "Osvaldo Palacios Flores",
		age: 25,
		weight: 87,
		height: 1.95,
		country: "mx",
	},
	{
		id: "el-mariana",
		name: "El Mariana",
		realName: "Osvaldo Palacios Flores",
		age: 25,
		weight: 87,
		height: 1.95,
		country: "mx",
	},
]

export const BOXERS_RIGHT: Boxer[] = [
	{
		id: "plex",
		name: "YoSoyPlex",
		realName: "Daniel Alonso Góndez",
		age: 22,
		weight: 70,
		height: 1.97,
		country: "es",
	},
	{
		id: "plex",
		name: "YoSoyPlex",
		realName: "Daniel Alonso Góndez",
		age: 22,
		weight: 70,
		height: 1.97,
		country: "es",
	},
	{
		id: "plex",
		name: "YoSoyPlex",
		realName: "Daniel Alonso Góndez",
		age: 22,
		weight: 70,
		height: 1.97,
		country: "es",
	},
	{
		id: "plex",
		name: "YoSoyPlex",
		realName: "Daniel Alonso Góndez",
		age: 22,
		weight: 70,
		height: 1.97,
		country: "es",
	},
	{
		id: "plex",
		name: "YoSoyPlex",
		realName: "Daniel Alonso Góndez",
		age: 22,
		weight: 70,
		height: 1.97,
		country: "es",
	},
	{
		id: "plex",
		name: "YoSoyPlex",
		realName: "Daniel Alonso Góndez",
		age: 22,
		weight: 70,
		height: 1.97,
		country: "es",
	},
	{
		id: "plex",
		name: "YoSoyPlex",
		realName: "Daniel Alonso Góndez",
		age: 22,
		weight: 70,
		height: 1.97,
		country: "es",
	},
	{
		id: "plex",
		name: "YoSoyPlex",
		realName: "Daniel Alonso Góndez",
		age: 22,
		weight: 70,
		height: 1.97,
		country: "es",
	},
	{
		id: "plex",
		name: "YoSoyPlex",
		realName: "Daniel Alonso Góndez",
		age: 22,
		weight: 70,
		height: 1.97,
		country: "es",
	},
	{
		id: "plex",
		name: "YoSoyPlex",
		realName: "Daniel Alonso Góndez",
		age: 22,
		weight: 70,
		height: 1.97,
		country: "es",
	},
	{
		id: "plex",
		name: "YoSoyPlex",
		realName: "Daniel Alonso Góndez",
		age: 22,
		weight: 70,
		height: 1.97,
		country: "es",
	},
]
