import type { Boxer } from "@/types/Boxer";

const addGetters = (boxers: Boxer[]): Boxer[] => {
    return boxers.map((b) => ({
        ...b,
        get age() {
            return new Date(new Date().getTime() - this.birthDate.getTime()).getFullYear() - 1970;
        },
        get allies() {
            return boxers.filter(
                (ally) => ally.versus === this.versus && ally.id !== this.id
            ).map((ally) => ally.id);
        },
    }));
}

//Datos ficticios
export const BOXERS: Boxer[] = addGetters([
    {
        id: "peereira",
        name: "Peereira",
        realName: "Peereira",
        gender: "masculino",
        birthDate: new Date(1988, 4, 15), 
        height: 1.78,
        weight: 74,
        age: 30,
        country: "es",
        versus: "rivaldios",
        guard: "Derecha",
        reach: 175,
        socials: {
            twitch: "",
            instagram: "",
            twitter: "",
            youtube: "",
            tiktok: "",
        },
        clips: [
			{
				text: "",
				url: "",
			}
		],
		rotate: true,
    },
    {
        id: "rivaldios",
        name: "Rivaldios",
        realName: "Rivaldios",
        gender: "masculino",
        birthDate: new Date(1991, 3, 22),
        height: 1.82,
        weight: 77,
        age: 30,
        country: "es",
        versus: "pereira",
        guard: "Izquierda",
        reach: 179,
        socials: {
            twitch: "",
            instagram: "",
            twitter: "",
            youtube: "",
            tiktok: "",
        },
    },
    {
        id: "perxitaa",
        name: "Perxitaa",
        realName: "Perxitaa",
        gender: "masculino",
        birthDate: new Date(1990, 7, 14),
        height: 1.75,
        age: 30,
        weight: 68,
        country: "es",
        versus: "gaspi",
        guard: "Izquierda",
        reach: 170,
        socials: {
            twitch: "",
            instagram: "",
            twitter: "",
            youtube: "",
            tiktok: "",
        },
    },
    {
        id: "gaspi",
        name: "Gaspi",
        realName: "Gaspi",
        gender: "masculino",
        birthDate: new Date(1989, 11, 5),
        height: 1.80,
        weight: 72,
        age: 30,
        country: "es",
        versus: "perxitaa",
        guard: "Derecha",
        reach: 174,
        socials: {
            twitch: "",
            instagram: "",
            twitter: "",
            youtube: "",
            tiktok: "",
        },
    },
    {
        id: "abby",
        name: "Abby",
        realName: "Abby",
        gender: "femenino",
        birthDate: new Date(1993, 2, 19),
        height: 1.65,
        weight: 54,
        age: 30,
        country: "es",
        versus: "roro",
        guard: "Izquierda",
        reach: 162,
        socials: {
            twitch: "",
            instagram: "",
            twitter: "",
            youtube: "",
            tiktok: "",
        },
    },
    {
        id: "roro",
        name: "Roro",
        realName: "Roro",
        gender: "femenino",
        birthDate: new Date(1994, 6, 7),
        height: 1.68,
        weight: 56,
        age: 30,
        country: "es",
        versus: "abby",
        guard: "Derecha",
        reach: 165,
        socials: {
            twitch: "",
            instagram: "",
            twitter: "",
            youtube: "",
            tiktok: "",
        },
    },
    {
        id: "andoni",
        name: "Andoni",
        realName: "Andoni",
        gender: "masculino",
        birthDate: new Date(1992, 9, 16),
        height: 1.80,
        weight: 73,
        age: 30,
        country: "mex",
        versus: "Carlos",
        guard: "Izquierda",
        reach: 178,
        socials: {
            twitch: "",
            instagram: "",
            twitter: "",
            youtube: "",
            tiktok: "",
        },
    },
    {
        id: "carlos",
        name: "Carlos",
        realName: "Carlos Belcast",
        gender: "masculino",
        birthDate: new Date(1990, 5, 23),
        height: 1.83,
        weight: 76,
        age: 30,
        country: "es",
        versus: "andoni",
        guard: "Derecha",
        reach: 181,
        socials: {
            twitch: "",
            instagram: "",
            twitter: "",
            youtube: "",
            tiktok: "",
        },
    },
    {
        id: "alana",
        name: "Alana",
        realName: "Alana",
        gender: "femenino",
        birthDate: new Date(1995, 3, 18),
        height: 1.70,
        weight: 60,
        age: 30,
        country: "es",
        versus: "ari-geli",
        guard: "Izquierda",
        reach: 169,
        socials: {
            twitch: "",
            instagram: "",
            twitter: "",
            youtube: "",
            tiktok: "",
        },
    },
    {
        id: "arigeli",
        name: "AriGeli",
        realName: "Ari geli",
        gender: "femenino",
        birthDate: new Date(1996, 7, 22),
        height: 1.67,
        weight: 58,
        age: 30,
        country: "es",
        versus: "alana",
        guard: "Derecha",
        reach: 166,
        socials: {
            twitch: "",
            instagram: "",
            twitter: "",
            youtube: "",
            tiktok: "",
        },
    },
    {
        id: "viruzz",
        name: "Viruzz",
        realName: "Viruzz",
        gender: "masculino",
        birthDate: new Date(1987, 1, 30),
        height: 1.85,
        weight: 78,
        age: 30,
        country: "es",
        versus: "tomas",
        guard: "Izquierda",
        reach: 182,
        socials: {
            twitch: "",
            instagram: "",
            twitter: "",
            youtube: "",
            tiktok: "",
        },
    },
    {
        id: "tomas",
        name: "tomas",
        realName: "Tomás Mazza",
        gender: "masculino",
        birthDate: new Date(1991, 4, 11),
        height: 1.88,
        weight: 82,
        age: 30,
        country: "es",
        versus: "viruzz",
        guard: "Derecha",
        reach: 185,
        socials: {
            twitch: "",
            instagram: "",
            twitter: "",
            youtube: "",
            tiktok: "",
        },
    },
    {
        id: "grefg",
        name: "Grefg",
        realName: "grefg",
        gender: "masculino",
        birthDate: new Date(1997, 4, 24),
        height: 1.75,
        weight: 70,
        age: 30,
        country: "es",
        versus: "westcol",
        guard: "Izquierda",
        reach: 174,
        socials: {
            twitch: "",
            instagram: "",
            twitter: "",
            youtube: "",
            tiktok: "",
        },
    },
    {
        id: "westcol",
        name: "Westcol",
        realName: "Westcol",
        gender: "masculino",
        birthDate: new Date(1995, 6, 19),
        height: 1.80,
        weight: 74,
        age: 30,
        country: "col",
        versus: "grefg",
        guard: "Derecha",
        reach: 179,
        socials: {
            twitch: "",
            instagram: "",
            twitter: "",
            youtube: "",
            tiktok: "",
        },
    }
]);
