interface Boxer {
	id: string
	name: string
	age: number
	realName: string
	weight: number
	height: number
	country: string
}

export const BOXERS: Boxer[] = [
	{
		id: "el-mariana",
		name: "El Mariana",
		realName: "Osvaldo Palacios Flores",
		age: 25,
		weight: 87,
		height: 1.95,
		country: "mx",
	},
	{
		id: "plex",
		name: "YoSoyPlex",
		realName: "Daniel Alonso Góndez",
		age: 22,
		weight: 70,
		height: 1.97,
		country: "es",
	},
	{
		id: "el-mariana",
		name: "El Mariana",
		realName: "Osvaldo Palacios Flores",
		age: 25,
		weight: 87,
		height: 1.95,
		country: "mx",
	},
	{
		id: "plex",
		name: "YoSoyPlex",
		realName: "Daniel Alonso Góndez",
		age: 22,
		weight: 70,
		height: 1.97,
		country: "es",
	},
	{
		id: "el-mariana",
		name: "El Mariana",
		realName: "Osvaldo Palacios Flores",
		age: 25,
		weight: 87,
		height: 1.95,
		country: "mx",
	},
	{
		id: "plex",
		name: "YoSoyPlex",
		realName: "Daniel Alonso Góndez",
		age: 22,
		weight: 70,
		height: 1.97,
		country: "es",
	},
	{
		id: "el-mariana",
		name: "El Mariana",
		realName: "Osvaldo Palacios Flores",
		age: 25,
		weight: 87,
		height: 1.95,
		country: "mx",
	},
	{
		id: "plex",
		name: "YoSoyPlex",
		realName: "Daniel Alonso Góndez",
		age: 22,
		weight: 70,
		height: 1.97,
		country: "es",
	},
	{
		id: "el-mariana",
		name: "El Mariana",
		realName: "Osvaldo Palacios Flores",
		age: 25,
		weight: 87,
		height: 1.95,
		country: "mx",
	},
	{
		id: "plex",
		name: "YoSoyPlex",
		realName: "Daniel Alonso Góndez",
		age: 22,
		weight: 70,
		height: 1.97,
		country: "es",
	},
	{
		id: "el-mariana",
		name: "El Mariana",
		realName: "Osvaldo Palacios Flores",
		age: 25,
		weight: 87,
		height: 1.95,
		country: "mx",
	},
	{
		id: "plex",
		name: "YoSoyPlex",
		realName: "Daniel Alonso Góndez",
		age: 22,
		weight: 70,
		height: 1.97,
		country: "es",
	},
	{
		id: "el-mariana",
		name: "El Mariana",
		realName: "Osvaldo Palacios Flores",
		age: 25,
		weight: 87,
		height: 1.95,
		country: "mx",
	},
	{
		id: "plex",
		name: "YoSoyPlex",
		realName: "Daniel Alonso Góndez",
		age: 22,
		weight: 70,
		height: 1.97,
		country: "es",
	},
	{
		id: "el-mariana",
		name: "El Mariana",
		realName: "Osvaldo Palacios Flores",
		age: 25,
		weight: 87,
		height: 1.95,
		country: "mx",
	},
	{
		id: "plex",
		name: "YoSoyPlex",
		realName: "Daniel Alonso Góndez",
		age: 22,
		weight: 70,
		height: 1.97,
		country: "es",
	},
	{
		id: "el-mariana",
		name: "El Mariana",
		realName: "Osvaldo Palacios Flores",
		age: 25,
		weight: 87,
		height: 1.95,
		country: "mx",
	},
	{
		id: "plex",
		name: "YoSoyPlex",
		realName: "Daniel Alonso Góndez",
		age: 22,
		weight: 70,
		height: 1.97,
		country: "es",
	},
	{
		id: "el-mariana",
		name: "El Mariana",
		realName: "Osvaldo Palacios Flores",
		age: 25,
		weight: 87,
		height: 1.95,
		country: "mx",
	},
	{
		id: "plex",
		name: "YoSoyPlex",
		realName: "Daniel Alonso Góndez",
		age: 22,
		weight: 70,
		height: 1.97,
		country: "es",
	},
	{
		id: "el-mariana",
		name: "El Mariana",
		realName: "Osvaldo Palacios Flores",
		age: 25,
		weight: 87,
		height: 1.95,
		country: "mx",
	},
	{
		id: "plex",
		name: "YoSoyPlex",
		realName: "Daniel Alonso Góndez",
		age: 22,
		weight: 70,
		height: 1.97,
		country: "es",
	},
	/* {
		id: "sezar-blue",
		name: "Sezar Blue",
		realName: "César González",
		age: 50,
		weight: 87,
		height: 1.77,
		country: "es",
	},
	{
		id: "will",
		name: "Will",
		realName: "Ángelo Valdés",
		age: 23,
		weight: 85, // No encontrado
		height: 1.85, // No encontrado
		country: "do",
	},
	{
		id: "peldanyos",
		name: "Peldanyos",
		realName: "Sergio Bolaños",
		age: 25,
		weight: 87, // No encontrado
		height: 1.91, // No es seguro
		country: "es",
	},
	{
		id: "aldo-geo",
		name: "Aldo Geo",
		realName: "Aldo Geovanni",
		age: 27,
		weight: 80, // No encontrado
		height: 1.79,
		country: "mx",
	},
	{
		id: "pelicanger",
		name: "Pelicanger",
		realName: "Angerson Esneider",
		age: 23,
		weight: 85, // No es seguro
		height: 1.91,
		country: "co",
	},
	{
		id: "roberto-cein",
		name: "RobertoCein",
		realName: "Roberto Sebastián Guadarrama Jiménez",
		age: 25,
		weight: 85, // No encontrado
		height: 1.69, // No es seguro
		country: "mx",
	},
	{
		id: "unicornio",
		name: "Unicornio",
		realName: "Germán Usinger",
		age: 24,
		weight: 75, // No encontrado
		height: 1.69, // No es seguro
		country: "ar",
	},
	{
		id: "karchez",
		name: "Karchez",
		realName: "José Carlos Sánchez",
		age: 23,
		weight: 85, // No encontrado
		height: 1.84,
		country: "es",
	},
	{
		id: "skain",
		name: "Skain",
		realName: "David Carbó Ferrer",
		age: 27,
		weight: 83, // No encontrado
		height: 1.83, // No encontrado
		country: "es",
	},
	{
		id: "folagor",
		name: "Folagor",
		realName: "Yoel Ramírez Pulido",
		age: 29,
		weight: 71,
		height: 1.8,
		country: "es",
	},
	{
		id: "shelao",
		name: "Shelao",
		realName: "Cristóbal Andrés Álvarez Leiva",
		age: 33,
		weight: 93,
		height: 1.88,
		country: "cl",
	},
	{
		id: "viruzz",
		name: "Viruzz",
		realName: "Víctor Mélida Cambra",
		age: 31,
		weight: 85,
		height: 1.82,
		country: "es",
	},
	{
		id: "ama-blitz",
		name: "Ama Blitz",
		realName: "Amairani Garza Alonso",
		age: 29, // No es seguro
		weight: 55, // No es seguro
		height: 1.58,
		country: "mx",
	},
	{
		id: "alana",
		name: "Alana",
		realName: "Alana Flores",
		age: 23,
		weight: 55,
		height: 1.7,
		country: "mx",
	},
	{
		id: "zeling",
		name: "Zeling",
		realName: "Alicia González",
		age: 28,
		weight: 65, // No encontrado
		height: 1.7, // No es seguro
		country: "es",
	},
	{
		id: "nissaxter",
		name: "Nissaxter",
		realName: "Cristina Magadán",
		age: 29,
		weight: 55, // No es seguro
		height: 1.64,
		country: "es",
	},
	{
		id: "la-cobra",
		name: "La Cobra",
		realName: "Lautaro Damián del Campo",
		age: 26,
		weight: 105,
		height: 1.83,
		country: "ar",
	},
	{
		id: "guanyar",
		name: "Guanyar",
		realName: "Diego Iglesias",
		age: 25,
		weight: 85,
		height: 1.88,
		country: "es",
	},
	{
		id: "agustin-51",
		name: "Agustin51",
		realName: "José Agustín Peréz Nuñéz",
		age: 23,
		weight: 62, // No es seguro
		height: 1.7,
		country: "es",
	},
	{
		id: "carrera",
		name: "Carreraaa",
		realName: "Rodrigo Ezequiel Carrera",
		age: 23,
		weight: 61,
		height: 1.65,
		country: "ar",
	}, */
] as const
