export const FIGHTERS = [
  {
    id: 'peereira',
    name: 'Peereira',
    bio: 'El streamer español Peereira7 es un creador de contenido de eSports. Combina sus directos en videojuegos como Valorant o Fortnite con otros contenidos IRL y de viajes. Futbolero y fan del RC Deportivo de la Coruña, su nombre real es Pablo y uno de sus motes, además de Pereira, es "El Gorras". 163 centímetros de mala baba, ideal para dejarlo todo en el ring.',
    realName: 'Pablo Pereira Ramos',
    gender: 'masculino',
    birthDate: new Date(1998, 11, 21),
    height: 1.63,
    age: 26,
    weight: 63,
    country: 'es',
    gallery: true,
    city: 'A Coruña, Galicia',
    versus: 'rivaldios',
  },
  {
    id: 'perxitaa',
    name: 'Perxitaa',
    bio: 'El youtuber y streamer español Perxitaa es una auténtica leyenda, desde sus comienzos en videojuegos como Minecraft, GTA o Fortnite hasta su andadura más reciente como presidente de Los Troncos FC de la Kings League. Jaume Cremades, arquitecto, es todo un grande también en lo físico. Y se entregará al máximo.',
    realName: 'Jaume Cremades Gradoli',
    gender: 'masculino',
    birthDate: new Date(1991, 6, 9),
    height: 1.86,
    age: 33,
    city: 'Catarroja, Valencia',
    weight: 102,
    country: 'es',
    gallery: true,
    versus: 'gaspi',
  },
  {
    id: 'abby',
    name: 'Abby',
    bio: 'Creadora de contenido y streamer conocida por su fuerte personalidad y contenido directo.',
    realName: 'Abby',
    gender: 'femenino',
    height: 1.65,
    age: 25,
    weight: 55,
    country: 'es',
    gallery: true,
    versus: 'roro',
  },
  {
    id: 'roro',
    name: 'Roro',
    bio: 'Creadora de contenido conocida por su aparente dulzura que contrasta con su personalidad real.',
    realName: 'Roro',
    gender: 'femenino',
    height: 1.60,
    age: 24,
    weight: 52,
    country: 'es',
    gallery: true,
    versus: 'abby',
  },
  {
    id: 'andoni',
    name: 'Andoni',
    bio: 'Culturista y creador de contenido especializado en fitness y musculación.',
    realName: 'Andoni',
    gender: 'masculino',
    height: 1.80,
    age: 28,
    weight: 95,
    country: 'es',
    gallery: true,
    versus: 'carlos',
  },
  {
    id: 'carlos',
    name: 'Carlos Belcast',
    bio: 'Culturista y creador de contenido especializado en fitness y musculación.',
    realName: 'Carlos Belcast',
    gender: 'masculino',
    height: 1.85,
    age: 30,
    weight: 100,
    country: 'es',
    gallery: true,
    versus: 'andoni',
  },
  {
    id: 'alana',
    name: 'Alana',
    bio: 'Creadora de contenido y deportista española conocida por su preparación física y boxeo.',
    realName: 'Alana',
    gender: 'femenino',
    height: 1.70,
    age: 26,
    weight: 58,
    country: 'es',
    gallery: true,
    versus: 'arigeli',
  },
  {
    id: 'arigeli',
    name: 'Ari Geli',
    bio: 'Creadora de contenido mexicana y deportista que se enfrentará a Alana en el ring.',
    realName: 'Ari Geli',
    gender: 'femenino',
    height: 1.68,
    age: 25,
    weight: 56,
    country: 'mx',
    gallery: true,
    versus: 'alana',
  },
  {
    id: 'viruzz',
    name: 'Viruzz',
    bio: 'Veterano creador de contenido y boxeador experimentado.',
    realName: 'Viruzz',
    gender: 'masculino',
    height: 1.75,
    age: 32,
    weight: 75,
    country: 'es',
    gallery: true,
    versus: 'tomas',
  },
  {
    id: 'tomas',
    name: 'Tomas Mazza',
    bio: 'Creador de contenido argentino y boxeador, representando la savia nueva.',
    realName: 'Tomas Mazza',
    gender: 'masculino',
    height: 1.78,
    age: 27,
    weight: 72,
    country: 'ar',
    gallery: true,
    versus: 'viruzz',
  },
  {
    id: 'grefg',
    name: 'The Grefg',
    bio: 'Uno de los más grandes creadores de contenido en habla hispana, conocido por su preparación física.',
    realName: 'The Grefg',
    gender: 'masculino',
    height: 1.82,
    age: 29,
    weight: 80,
    country: 'es',
    gallery: true,
    versus: 'westcol',
  },
  {
    id: 'westcol',
    name: 'Westcol',
    bio: 'Creador de contenido colombiano que se enfrentará a The Grefg en el main event.',
    realName: 'Westcol',
    gender: 'masculino',
    height: 1.80,
    age: 28,
    weight: 78,
    country: 'co',
    gallery: true,
    versus: 'grefg',
  },
  {
    id: 'rivaldios',
    name: 'Rivaldios',
    bio: 'Creador de contenido que se enfrentará a Peereira en el primer combate de la noche.',
    realName: 'Rivaldios',
    gender: 'masculino',
    height: 1.70,
    age: 27,
    weight: 68,
    country: 'es',
    gallery: true,
    versus: 'peereira',
  },
  {
    id: 'gaspi',
    name: 'Gaspi',
    bio: 'Creador de contenido que se enfrentará a Perxitaa en un combate de mucha altura y peso.',
    realName: 'Gaspi',
    gender: 'masculino',
    height: 1.88,
    age: 31,
    weight: 105,
    country: 'es',
    gallery: true,
    versus: 'perxitaa',
  },
] 