import type { Fighters } from '@/types/fighters'
import X from '@/assets/svg/x.svg'
import Instagram from '@/assets/svg/instagram.svg'
import Youtube from '@/assets/svg/youtube.svg'
import TikTok from '@/assets/svg/tiktok.svg'
import Twitch from '@/assets/svg/twitch.svg'
import Kick from '@/assets/svg/kick.svg'

export const FIGHTERS: Fighters[] = [
  {
    // https://www.biografia.de/peereira/
    id: 'peereira',
    name: 'Peereira',
    bio: 'El streamer español Peereira7 es un creador de contenido de eSports. Combina sus directos en videojuegos como Valorant o Fortnite con otros contenidos IRL y de viajes. Futbolero y fan del RC Deportivo de la Coruña, su nombre real es Pablo y uno de sus motes, además de Pereira, es ‘El Gorras’. 163 centímetros de mala baba, ideal para dejarlo todo en el ring.',
    realName: 'Pablo Pereira Ramos',
    gender: 'masculino',
    birthDate: new Date(1998, 11, 21),
    height: 1.63,
    age: 26,
    weight: 63,
    country: 'es',
    gallery: true,
    city: 'A Coruña, Galicia',
    versus: 'rivaldios',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/peereira7',
        label: 'Visitar perfil de Peereira en Instagram',
        followers: '220k',
        image: {
          logo: Instagram,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/@peereira7',
        label: 'Visitar perfil de Peereira en TikTok',
        followers: '585k',
        image: {
          logo: TikTok,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'youtube',
        name: 'Youtube',
        url: 'https://www.youtube.com/channel/UCOBtOqxsioUI-fFykO2I4BQ',
        label: 'Visitar canal de Peereira en Youtube',
        followers: '434k',
        image: {
          logo: Youtube,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'x',
        name: 'X',
        url: 'https://x.com/Peereira7',
        label: 'Visitar perfil de Peereira en X',
        followers: '310k',
        image: {
          logo: X,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'twitch',
        name: 'Twitch',
        url: 'https://www.twitch.tv/peereira7',
        label: 'Visitar perfil de Peereira en Twitch',
        followers: '1.3M',
        image: {
          logo: Twitch,
          width: 200,
          height: 200,
        },
      },
    ],
    clips: [
      {
        text: 'En seis meses va a caer, lo voy a noquear 100% y le voy a arrancar la p*** cabeza.',
        url: 'https://www.youtube.com/embed/OjOItlQQHNM?si=GIR26FtonnzIbZZL&amp;clip=UgkxLQNqwPqlJLU97lVJkD2lEWrJXswPfHOU&amp;clipt=ENGYChjaywo',
      },
      {
        text: 'Vengo aquí para ser el mejor boxeador posible, estoy con el mejor equipo posible y lo único que te pido es que entrenes lo suficientemente bien para que toda esta gente vea el show que se merece.',
        url: 'https://www.youtube.com/embed/OjOItlQQHNM?si=OQAXdqDuQ33flPQg&amp;clip=UgkxtAMxt3Q-BIOC7G6PqfRTs8qkUZgaXwWP&amp;clipt=ENS2KBjkiik',
      },
      {
        text: 'Entreno literalmente para noquearlo, no vengo a otra cosa.',
        url: 'https://www.youtube.com/embed/OjOItlQQHNM?si=AOlsjKIAacuwz_NZ&amp;clip=Ugkx2wfrvLVecdcny4Aw7hy0wu44LEZ8p3Ua&amp;clipt=EI2IQhiVr0I',
      },
    ],
    workout: {
      videoID: 'msvzME2RPu0',
      thumbnail: '/images/fighters/workoutThumbnails/peereira-thumbnail.webp',
    },
  },
  {
    // https://laletrade.com/biografias/twitch/18087-perxitaa
    id: 'perxitaa',
    name: 'Perxitaa',
    bio: 'El youtuber y streamer español Perxitaa es una auténtica leyenda, desde sus comienzos en videojuegos como Minecraft, GTA o Fortnite hasta su andadura más reciente como presidente de Los Troncos FC de la Kings League. Jaume Cremades, arquitecto, es todo un grande también en lo físico. Y se entregará al máximo.',
    realName: 'Jaume Cremades Gradoli',
    gender: 'masculino',
    birthDate: new Date(1991, 6, 9),
    height: 1.86,
    age: 33,
    city: 'Catarroja, Valencia',
    weight: 102,
    country: 'es',
    gallery: true,
    versus: 'gaspi',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/perxitaa',
        label: 'Visitar perfil de Perxitaa en Instagram',
        followers: '1.1M',
        image: {
          logo: Instagram,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/@srperxitaa',
        label: 'Visitar perfil de Perxitaa en TikTok',
        followers: '349.7k',
        image: {
          logo: TikTok,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'youtube',
        name: 'Youtube',
        url: 'https://www.youtube.com/@perxitaa',
        label: 'Visitar perfil de Perxitaa en Youtube',
        followers: '2.53M',
        image: {
          logo: Youtube,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'x',
        name: 'X',
        url: 'https://x.com/Perxitaa',
        label: 'Visitar perfil de Perxitaa en X',
        followers: '2.1M',
        image: {
          logo: X,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'twitch',
        name: 'Twitch',
        url: 'https://www.twitch.tv/perxitaa',
        label: 'Visitar perfil de Perxitaa en Twitch',
        followers: '2.5M',
        image: {
          logo: Twitch,
          width: 200,
          height: 200,
        },
      },
    ],
    clips: [
      {
        text: 'Me es indiferente, me adaptaré a lo que toque, competiremos y ganaremos. Es que no veo otro escenario.',
        url: 'https://www.youtube.com/embed/aOKOUIx8mPU?si=ao2b-RL5rdAkoTXY&amp;clip=Ugkx5nWUXM5WtVO9Bf3Nf3hJ1BkQP_ZY6TO9&amp;clipt=ELTuGxinpBw',
      },
      {
        text: 'Creo que este es un reto, porque lo veo grande, lo veo que va a pegar fuerte. Voy a tener que pegar el doble de fuerte.',
        url: 'https://www.youtube.com/embed/aOKOUIx8mPU?si=Fjv_96aIwtSIFxsD&amp;clip=UgkxjZakldIAOdYJdcaksZax_wQZIrZ7nq9m&amp;clipt=EKzsGhijmhs',
      },
      {
        text: '¿Va a ser una pelea de boxeo o una pelea de sumo?',
        url: 'https://www.youtube.com/embed/aOKOUIx8mPU?si=k_vt7-vi3PoyKjnp&amp;clip=UgkxWCffIotsU0x8oWW2HPc8sqFlY5EKtZ2r&amp;clipt=EJiLDRigsg0',
      },
      {
        text: 'Llevas el mismo traje hace 4 dias.',
        url: 'https://www.youtube.com/embed/aOKOUIx8mPU?si=5vHVGPD2lSLWPKGE&amp;clip=UgkxZ65f4VwWoQJLjI0oTYCpoiIxt5klwwY-&amp;clipt=EPzFCRiE7Qk',
      },
    ],
    workout: {
      videoID: 'dj-4LLi5cck',
      thumbnail: '/images/fighters/workoutThumbnails/perxitaa-thumbnail.webp',
    },
  },
  {
    // https://www.biografia.de/abby/
    id: 'abby',
    name: 'Abby',
    bio: 'Abby es una streamer española que ha construido una gran comunidad jugando a League of Legends desde hace años, pero poco a poco ha ido ampliando y enriqueciendo su contenido con nuevos enfoques. Ganadora del concurso ‘El último en pie’ de Ibai en 2022, Abril Gené fue crítica con el contenido y formato de su oponente Roro. Es el momento de llevar esa rivalidad al cuadrilátero.',
    realName: 'Abril Gené Capriles',
    gender: 'femenino',
    birthDate: new Date(2000, 11, 28),
    height: 1.72,
    age: 24,
    weight: 62,
    country: 'es',
    gallery: true,
    city: 'Palma, Mallorca',
    versus: 'roro',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/abbyimu/',
        label: 'Visitar perfil de Abby en Instagram',
        followers: '332k',
        image: {
          logo: Instagram,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/@abbyimu',
        label: 'Visitar perfil de Abby en TikTok',
        followers: '794.9k',
        image: {
          logo: TikTok,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'youtube',
        name: 'Youtube',
        url: 'https://www.youtube.com/@abbyimu',
        label: 'Visitar canal de Abby en Youtube',
        followers: '175k',
        image: {
          logo: Youtube,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'x',
        name: 'X',
        url: 'https://x.com/abbyiimu',
        label: 'Visitar perfil de Abby en X',
        followers: '620.8k',
        image: {
          logo: X,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'twitch',
        name: 'Twitch',
        url: 'https://www.twitch.tv/abby_',
        label: 'Visitar perfil de Abby en Twitch',
        followers: '626k',
        image: {
          logo: Twitch,
          width: 200,
          height: 200,
        },
      },
    ],
    clips: [
      {
        text: 'No sé cómo ha aceptado esta pelea, la verdad.',
        url: 'https://www.youtube.com/embed/_A0QFge7TlI?si=vZ8QPx7N3N3b8pPG&amp;clip=UgkxneRcG-WbxSh6Vsz4bAXq_sNFOJlXNP6z&amp;clipt=EJDxHhiUwx8',
      },
      {
        text: 'Cuando Roro me tenga delante en el ring... va a sentir miedo.',
        url: 'https://www.youtube.com/embed/_A0QFge7TlI?si=PNqW7cYn-m5SIrXX&amp;clip=Ugkxgnawy6NKH7cVWFX5fhgf3ZvfaGVfzInm&amp;clipt=ELCcGxjp3Bs',
      },
      {
        text: 'Esto es algo que tenía que pasar... A ver, Roro, si estás preparada.',
        url: 'https://www.youtube.com/embed/_A0QFge7TlI?si=KH5GLwytjfIaqnuC&amp;clip=UgkxtRthPKbk_vfmyz7EmhYbhskD5mDJcXCd&amp;clipt=EO2_BRjNpgY',
      },
    ],
    workout: {
      videoID: 'HBTuF3KONZc',
      thumbnail: '/images/fighters/workoutThumbnails/abby-thumbnail.webp',
    },
  },
  {
    // https://www.biografia.de/roro/
    id: 'roro',
    name: 'Roro',
    bio: 'Probablemente la tiktoker revelación de los últimos tiempos, Roro tiene una mano especial para cocinar y preparar recetas increíbles desde cero, unidas a una creatividad que la han catapultado al éxito. Rocío viene de participar recientemente en un ‘talent show’ de cocina en televisión y pocos saben que sus primeros vídeos en redes eran en el gimnasio. ¿Es Roro una ‘gymbro’? Disciplina y motivación no le faltan para ponerse el cinturón.',
    realName: 'Rocío López Bueno',
    gender: 'femenino',
    birthDate: new Date(2002, 2, 1),
    height: 1.49,
    age: 23,
    weight: 47,
    country: 'es',
    gallery: true,
    city: 'Barcelona, Cataluña',
    versus: 'abby',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/whoisroro/',
        label: 'Visitar perfil de Roro en Instagram',
        followers: '3.3M',
        image: {
          logo: Instagram,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/@roro.bueno',
        label: 'Visitar perfil de Roro en TikTok',
        followers: '8.1M',
        image: {
          logo: TikTok,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'youtube',
        name: 'Youtube',
        url: 'https://www.youtube.com/@roroobuenoo',
        label: 'Visitar canal de Roro en Youtube',
        followers: '92.5k',
        image: {
          logo: Youtube,
          width: 200,
          height: 200,
        },
      },
    ],
    clips: [
      {
        text: 'Nunca voy a hundir a una mujer para sentirme mejor conmigo misma.',
        url: 'https://www.youtube.com/embed/_A0QFge7TlI?si=lBVhjXJ2Zn7cbrch&amp;clip=Ugkxu-CzMHs-3zLGaFFCGIh-tcPMjImucfAT&amp;clipt=EOnqLRjv0y4',
      },
      {
        text: 'Si me enfadas, no te voy a sonreír.',
        url: 'https://www.youtube.com/embed/_A0QFge7TlI?si=toSZw_B6pu-wvkej&amp;clip=Ugkx343aGQvxi3px_edJLMmiUwfmyRIZGyB5&amp;clipt=EIzLLBiXoC0',
      },
      {
        text: 'Yo tengo la disciplina para prepararme lo mejor que yo pueda.',
        url: 'https://www.youtube.com/embed/_A0QFge7TlI?si=_mA5-y8p57kbFYUS&amp;clip=UgkxFEJaIdinVMKPzvTr575aHeDFcG7x60TN&amp;clipt=EOSaOhi7gzs',
      },
    ],
  },
  {
    // https://www.biografia.de/gaspi/
    id: 'gaspi',
    name: 'Gaspi',
    bio: 'El rey de la improvisación, el argentino Gaspi desconoce el significado de la palabra vergüenza cuando tiene un micrófono en la mano. Sus bromas pesadas y chistes en cualquier rincón, calle, tienda o bar, regalan clips de oro con una frecuencia asombrosa. Su voz y sonidos indescriptibles despistan a cualquiera. ¿Alguien puede imaginarse qué personalidad mostrará sobre el ring? Solo él lo sabe.',
    realName: 'Gaspar Prim Díaz',
    gender: 'masculino',
    birthDate: new Date(2002, 11, 28),
    height: 1.83,
    age: 22,
    weight: 112,
    country: 'ar',
    gallery: true,
    city: 'Buenos Aires',
    versus: 'perxitaa',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/gaspipd/',
        label: 'Visitar perfil de Gaspi en Instagram',
        followers: '1.7M',
        image: {
          logo: Instagram,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/@gaspipdd',
        label: 'Visitar perfil de Gaspi en TikTok',
        followers: '1.5M',
        image: {
          logo: TikTok,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'youtube',
        name: 'Youtube',
        url: 'https://www.youtube.com/GaspiPD',
        label: 'Visitar canal de Gaspi en Youtube',
        followers: '2.41M',
        image: {
          logo: Youtube,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'x',
        name: 'X',
        url: 'https://x.com/gaspipd',
        label: 'Visitar perfil de Gaspi en X',
        followers: '570.4k',
        image: {
          logo: X,
          width: 200,
          height: 200,
        },
      },
    ],
    clips: [
      {
        text: 'Perxitaa, mira que la vida real no es como el Minecraft… pasan cosas afuera.',
        url: 'https://www.youtube.com/embed/aOKOUIx8mPU?si=xe0_jPqJ7lBEMNDx&amp;clip=UgkxVZqXUgbXM15VuQBnVAg38-8W2PnL8oqT&amp;clipt=EJDeAxiYhQQ&autoplay=1',
      },
      {
        text: 'Te vi haciendo videitos. ¿Vas a pelear con el joystick o con el teclado y el mouse?',
        url: 'https://www.youtube-nocookie.com/embed/aOKOUIx8mPU?si=up7KtwZu2l3qEfmY&amp;clip=Ugkxf1_rx09dGrsr69Wdu2-Bi1wq8BvACp2f&amp;clipt=EPYLBjYjA0',
      },
      {
        text: 'Me dijiste que era contra el Rubius. ¿Quién es ese?',
        url: 'https://www.youtube-nocookie.com/embed/aOKOUIx8mPU?si=wsz9otQaciQnFKsV&amp;clip=UgkxGw6p-ksOymoiuVHBCw5Mx5UUmZqrAiY8&amp;clipt=EJycBxjRwwc',
      },
    ],
  },
  {
    // https://www.biografia.de/rivaldios/
    id: 'rivaldios',
    name: 'Rivaldios',
    bio: 'El tiktoker mexicano Rivaldios es uno de los grandes creadores latinoamericanos especializados en contenido de fútbol. Como jugador, llegó a progresar en las categorías inferiores de distintos equipos profesionales antes de centrar su futuro como influencer deportivo. El de Sinaloa realiza retos de fútbol en redes, donde su zurda garantiza calidad. Ahora veremos cómo La Cabra se desenvuelve con los guantes.',
    realName: 'Rivaldo Reatiga Ojeda',
    gender: 'masculino',
    birthDate: new Date(2001, 1, 6),
    height: 1.7,
    age: 24,
    weight: 69,
    country: 'mx',
    gallery: true,
    city: 'Rosales, Culiacán',
    versus: 'peereira',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/rivaldios10/',
        label: 'Visitar perfil de Rivaldios en Instagram',
        followers: '1.4M',
        image: {
          logo: Instagram,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/@rivaldios10',
        label: 'Visitar perfil de Rivaldios en TikTok',
        followers: '5.1M',
        image: {
          logo: TikTok,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'youtube',
        name: 'Youtube',
        url: 'https://www.youtube.com/@Rivaldios-lacabra',
        label: 'Visitar canal de Rivaldios en Youtube',
        followers: '46.9k',
        image: {
          logo: Youtube,
          width: 200,
          height: 200,
        },
      },
    ],
    clips: [
      {
        text: 'Pereira, ponte trucha, amigo. Te voy a enseñar que la cuna del boxeo está en México.',
        url: 'https://www.youtube.com/embed/OjOItlQQHNM?si=2yNcYbYAnGXc4jRD&amp;clip=UgkxuVSmgfc49HRArsmT522Vf42fmDo_W1WA&amp;clipt=EKOABBj8rgQ',
      },
      {
        text: 'Voy a llegar al punto en que este v**** me va a tener miedo después de la pelea.',
        url: 'https://www.youtube.com/embed/OjOItlQQHNM?si=qXDaC9BtQVT2Lw3r&amp;clip=Ugkxyvlpe6cGZqC2A2tU6B_-kgYlAqHuWn90&amp;clipt=EJC-LxiY5S8',
      },
      {
        text: 'La sangre culichi está bien pesada, una vez que te metes con un culichi, papito, a ver si sales de ahí.',
        url: 'https://www.youtube.com/embed/OjOItlQQHNM?si=JZx9yIQa0lXP9BTh&amp;clip=Ugkxjn97-DOruGG1ClS3KgmuiNEMXRf5a4aj&amp;clipt=EJytRBjj4EQ',
      },
    ],
    workout: {
      videoID: 'bNwgdNDz4d4',
      thumbnail: '/images/fighters/workoutThumbnails/rivaldios-thumbnail.webp',
    },
  },
  {
    // https://www.biografia.de/andoni/
    id: 'andoni',
    name: 'Andoni',
    bio: 'Andoni Talledo es una promesa del culturismo en España que ha alcanzado una gran popularidad en internet con contenido sobre fitness y entrenamiento personal. Desde hace años comparte en redes su progreso físico hasta alcanzar el punto en el que está: es un auténtico animal. Su reto mayúsculo será bajar de peso alrededor de 15 kilos para adaptarse a los 100 en los que ha acordado el combate con Belcast.',
    realName: 'Andoni Talledo Gutiérrez',
    gender: 'masculino',
    birthDate: new Date(2003, 0, 3),
    height: 1.87,
    age: 22,
    weight: 115,
    country: 'es',
    gallery: true,
    city: 'San Sebastian, Guipúzcoa',
    versus: 'carlos',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/andonifitness/',
        label: 'Visitar perfil de Andoni en Instagram',
        followers: '2.9M',
        image: {
          logo: Instagram,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/@andoonig',
        label: 'Visitar perfil de Andoni en TikTok',
        followers: '4.8M',
        image: {
          logo: TikTok,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'youtube',
        name: 'Youtube',
        url: 'https://www.youtube.com/@AndoniFitness',
        label: 'Visitar canal de Andoni en Youtube',
        followers: '944k',
        image: {
          logo: Youtube,
          width: 200,
          height: 200,
        },
      },
    ],
    clips: [
      {
        text: 'Yo voy a ir obviamente a ganar, y que eso no afecte nuestra relación.',
        url: 'https://www.youtube.com/embed/NbaFxQiuFek?si=b9Sxnq2S0zG-74SV&amp;clip=Ugkx_ci1g5b732avNi7KVaeOw46sgni4lutX&amp;clipt=ELDMJBjYkiU',
      },
      {
        text: 'Cualquier puño de ambos, si entra, es un puño de una persona pesada. Entonces es muy probable que, si entra de manera contundente… pues que acabe.',
        url: 'https://www.youtube.com/embed/NbaFxQiuFek?si=mrqP0DjJ6dMTG3A9&amp;clip=UgkxOd-2XnnjkWi3KR1fp5cmGPP3s1yXdQqY&amp;clipt=ELjGGhiAlxs',
      },
      {
        text: 'Carlos y yo habíamos dicho que por cada puño íbamos a lanzarnos un ‘te amo’.',
        url: 'https://www.youtube.com/embed/NbaFxQiuFek?si=km59ayaLbPKm19qb&amp;clip=UgkxDfmm-4rtX6GmFfRRue8dNTsqDS2D4YbF&amp;clipt=EMG4Jhin6iY',
      },
    ],
    workout: {
      videoID: 'QDy_MM6y-7U',
      thumbnail: '/images/fighters/workoutThumbnails/andoni-thumbnail.webp',
    },
  },
  {
    // https://www.biografia.de/viruzz/
    id: 'viruzz',
    name: 'Viruzz',
    realName: 'Víctor Mélida Cambra',
    bio: 'El papá de La Velada, con dos cinturones ya y tres participaciones, Víctor Mélida, Viruzz va a por la cuarta. El formato se adapta a la perfección a este creador español que asegura una cosa: el mejor boxeo de la noche lo veremos con él en pie. Viruzz consiguió su redención tras las malas decisiones del pasado batiendo a Shelao en 2024 con un derechazo inmenso, probablemente el mejor golpe en la historia de las Veladas. Exjugador profesional de balonmano en Liga Asobal, su contenido va desde deportes hasta videojuegos, pasando por IRL, comida… ¿Podrá alcanzar la triple corona en Sevilla?',
    gender: 'masculino',
    birthDate: new Date(1992, 4, 1),
    height: 1.82,
    age: 32,
    weight: 87,
    country: 'es',
    city: 'Zaragoza, Aragón',
    versus: 'tomas',
    gallery: true,
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/victormelida/',
        label: 'Visitar perfil de Viruzz en Instagram',
        followers: '1.7M',
        image: {
          logo: Instagram,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/@victormelida',
        label: 'Visitar perfil de Viruzz en TikTok',
        followers: '1.6M',
        image: {
          logo: TikTok,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'youtube',
        name: 'Youtube',
        url: 'https://www.youtube.com/user/byViruZz',
        label: 'Visitar canal de Viruzz en Youtube',
        followers: '6.14M',
        image: {
          logo: Youtube,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'x',
        name: 'X',
        url: 'https://x.com/byViruZz',
        label: 'Visitar perfil de Viruzz en X',
        followers: '1.1M',
        image: {
          logo: X,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'twitch',
        name: 'Twitch',
        url: 'https://www.twitch.tv/byViruZz',
        label: 'Visitar perfil de Viruzz en Twitch',
        followers: '435k',
        image: {
          logo: Twitch,
          width: 200,
          height: 200,
        },
      },
    ],
    clips: [
      {
        text: 'Una de mis comidas favoritas la empanada argentina.',
        url: 'https://www.youtube.com/embed/t7r5O_5B-E0?si=1tlrUUKM-18eZlen&amp;clip=UgkxW9ZMSp3ZrKKJGaU3qR9kK2njuf0fgO-w&amp;clipt=EPPv0wQY-5bUBA',
      },
      {
        text: 'Estar de rival de visitante en otro país.',
        url: 'https://www.youtube.com/embed/t7r5O_5B-E0?si=IPvCjZ_-7K3fBW63&amp;clip=UgkxEmHfqcAo_spkOhqxLq0KHf7ZhmOMhUuB&amp;clipt=EJTM3QQY08beBA',
      },
    ],
    workout: {
      videoID: 'Uy48X5YxujI',
      thumbnail: '/images/fighters/workoutThumbnails/viruzz-thumbnail.webp',
    },
  },
  {
    // https://www.biografia.de/alana-flores/
    id: 'alana',
    name: 'Alana',
    bio: 'Presidenta de Raniza FC de la Kings League Américas, la mexicana Alana Flores vivirá su segunda participación en La Velada después de imponerse con claridad en el 2vs2 junto a Amablitz, destrozando a las españolas Zeling y Nissaxter el año pasado en el Santiago Bernabéu. Pese a la victoria, nos quedamos con ganas de más y ahora habrá mucha más Alana en el cuadrilátero. El boxeo y el deporte la han llevado a un brutal cambio físico que centra ahora su contenido, donde también hay videojuegos o IRL. Sin duda, una de las grandes streamers de Latinoamérica.',
    fightName: 'Alana La Rana',
    realName: 'Alana Scarlett Flores Fuentes',
    gender: 'femenino',
    birthDate: new Date(2000, 11, 15),
    height: 1.57,
    age: 24,
    weight: 51,
    targetWeight: 52,
    targetGloves: '12oz',
    country: 'mx',
    gallery: true,
    city: 'Monterrey, Nuevo León',
    versus: 'arigeli',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/alanafloresf/',
        label: 'Visitar perfil de Alana en Instagram',
        followers: '4.7M',
        image: {
          logo: Instagram,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/@alanafloresf',
        label: 'Visitar perfil de Alana en TikTok',
        followers: '6.5M',
        image: {
          logo: TikTok,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'youtube',
        name: 'Youtube',
        url: 'https://www.youtube.com/@alanafloresf',
        label: 'Visitar canal de Alana en Youtube',
        followers: '574k',
        image: {
          logo: Youtube,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'x',
        name: 'X',
        url: 'https://x.com/alanafloresf',
        label: 'Visitar perfil de Alana en X',
        followers: '1M',
        image: {
          logo: X,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'twitch',
        name: 'Twitch',
        url: 'https://www.twitch.tv/alanalarana',
        label: 'Visitar perfil de Alana en Twitch',
        followers: '922k',
        image: {
          logo: Twitch,
          width: 200,
          height: 200,
        },
      },
    ],
    clips: [
      {
        text: 'Llevas un año pidiendo probar mis guantes; por fin, te voy a dar el gusto.',
        url: 'https://www.youtube.com/embed/qdS_XOZ5kyU?si=ma0Sdomx1JJOyld1&amp;clip=Ugkxd-wfH9H1C-ZaiGBlFn3hZeAk9qQWK48w&amp;clipt=EKjUAhiw-wI',
      },
    ],
    workout: {
      videoID: 'TmC9TuD8NoQ',
      thumbnail: '/images/fighters/workoutThumbnails/alana-thumbnail.webp',
    },
  },
  {
    // https://laletrade.com/biografias/youtuber/espanol/22589-thegrefg
    id: 'grefg',
    name: 'Grefg',
    realName: 'David Cánovas Martínez',
    gender: 'masculino',
    birthDate: new Date(1997, 3, 24),
    height: 1.79,
    age: 27,
    weight: 74,
    country: 'es',
    gallery: true,
    city: 'Alhama de Murcia, Murcia',
    versus: 'westcol',
    bio: 'Un coloso de la creación de contenido, David Cánovas ‘TheGrefg’ ha pasado de sus comienzos subiendo gameplays a convertirse en un creador total. Copropietario de una de las grandes entidades de eSports, Team Heretics, organiza desde 2022 los Premios Esland que reconocen a los mejores creadores hispanohablantes. Para la historia queda su presentación de skin en Fortnite, que reunió en Twitch a casi 2,5 millones de espectadores, una cifra que solo las Veladas II, III y IV han podido superar. El presidente de los Saiyans FC de la Kings League viaja, prueba comida, juega a videojuegos, trabaja en un cambio físico que ya es brutal… y que puede ser clave para llevarse el cinturón.',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/TheGrefg/',
        label: 'Visitar perfil de Grefg en Instagram',
        followers: '7.4M',
        image: {
          logo: Instagram,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/@thegrefg?_t=8ffeaGxV7Lt&_r=1',
        label: 'Visitar perfil de Grefg en TikTok',
        followers: '9.1M',
        image: {
          logo: TikTok,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'youtube',
        name: 'Youtube',
        url: 'https://www.youtube.com/@TheGrefg',
        label: 'Visitar canal de Grefg en Youtube',
        followers: '19M',
        image: {
          logo: Youtube,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'x',
        name: 'X',
        url: 'https://x.com/TheGrefg',
        label: 'Visitar perfil de Grefg en X',
        followers: '8.4M',
        image: {
          logo: X,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'twitch',
        name: 'Twitch',
        url: 'https://www.twitch.tv/thegrefg',
        label: 'Visitar perfil de Grefg en Twitch',
        followers: '12.2M',
        image: {
          logo: Twitch,
          width: 200,
          height: 200,
        },
      },
    ],
    clips: [
      {
        text: 'Siempre gano; y si no, es porque no ha acabado.',
        url: 'https://www.youtube.com/embed/cfpvro5tD7g?si=rjaM5jJdImEtefJ6&amp;clip=UgkxuoAS_mblPPU-wtj4bH3GiLXmVRBAow2b&amp;clipt=EImsAhjj2gI',
      },
    ],
    workout: {
      videoID: '_Rh-VjB3ATk',
      thumbnail: '/images/fighters/workoutThumbnails/grefg-thumbnail.webp',
    },
  },
  {
    // https://www.biografia.de/westcol/
    id: 'westcol',
    name: 'Westcol',
    realName: 'Luis Fernando Villa Álvarez',
    gender: 'masculino',
    birthDate: new Date(2001, 1, 2),
    height: 1.65,
    age: 24,
    weight: 63,
    country: 'co',
    gallery: true,
    city: 'Ciudad Bolívar, Antioquia',
    versus: 'grefg',
    bio: 'El colombiano Luis Villa, Westcol, es uno de los streamers más populares y exitosos de Latinoamérica. Presidente junto al rapero Arcángel de West Santos FC de la Kings League Américas, su comunidad y números hablan por sí solos. Con contenido variado, incluyendo videojuegos y charlas con sus seguidores, entrevistas, etc, ha organizado hasta su propia velada de boxeo: la exitosa Stream Fighters. Recientemente se ha adentrado en el mundo de la música, colaborando con Beéle, Blessd u Ovy On The Drums en éxitos mundiales como Soltera y La Plena. Polémico y amante de la buena vida, la expectación es máxima por seguir su preparación para la gran cita.',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/westcol/',
        label: 'Visitar perfil de Westcol en Instagram',
        followers: '4.3M',
        image: {
          logo: Instagram,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/@westcol',
        label: 'Visitar perfil de Westcol en TikTok',
        followers: '993.4k',
        image: {
          logo: TikTok,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'youtube',
        name: 'Youtube',
        url: 'https://www.youtube.com/channel/UCEg_iK8FKwZfpRMn4-AnnnQ',
        label: 'Visitar canal de Westcol en Youtube',
        followers: '1.32M',
        image: {
          logo: Youtube,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'x',
        name: 'X',
        url: 'https://x.com/WestCOL',
        label: 'Visitar perfil de Westcol en X',
        followers: '413.3k',
        image: {
          logo: X,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'kick',
        name: 'Kick',
        url: 'https://www.kick.com/westcol',
        label: 'Visitar perfil de Westcol en Kick',
        followers: '1.9M',
        image: {
          logo: Kick,
          width: 200,
          height: 200,
        },
      },
    ],
    workout: {
      videoID: '_XWxZUwzhXk',
      thumbnail: '/images/fighters/workoutThumbnails/westcol-thumbnail.webp',
    },
    clips: [
      {
        text: 'Vamos a ver si le dan las hue***.',
        url: 'https://www.youtube.com/embed/cfpvro5tD7g?si=ZcMgqxaAfHxRQb96&amp;clip=UgkxQ5sj8mAkLsReNNl3UPmr5g6CkSbZyERl&amp;clipt=EKjXAhiw_gI',
      },
    ],
  },
  {
    // https://www.biografia.de/ari-geli/
    id: 'arigeli',
    name: 'Arigeli',
    bio: 'Jugadora de baloncesto y creadora deportiva, Ari Geli ha viajado por todo el mundo con un balón en las manos y es propietaria y fundadora del equipo Panthers3x3. Su contenido siempre centrado en deporte y con buen humor le ha impulsado a hitos como el de mejor creador referente en deportes en España en 2022. Su forma de enfocar, por ejemplo, las lesiones deportivas y su recuperación ha contribuido sin duda al gran crecimiento de Pitufina, la reina de los triples.',
    realName: 'Ariadna Geli Pérez',
    gender: 'femenino',
    birthDate: new Date(2002, 9, 11),
    height: 1.58,
    age: 22,
    weight: 53,
    country: 'es',
    gallery: true,
    city: 'Barcelona, Cataluña',
    versus: 'alana',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/arigelii/',
        label: 'Visitar perfil de Arigeli en Instagram',
        followers: '1.2M',
        image: {
          logo: Instagram,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/@arigeli',
        label: 'Visitar perfil de Arigeli en TikTok',
        followers: '3.4M',
        image: {
          logo: TikTok,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'youtube',
        name: 'Youtube',
        url: 'https://www.youtube.com/@AriGeli',
        label: 'Visitar canal de Arigeli en Youtube',
        followers: '466k',
        image: {
          logo: Youtube,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'x',
        name: 'X',
        url: 'https://x.com/ariigelii',
        label: 'Visitar perfil de Arigeli en X',
        followers: '28k',
        image: {
          logo: X,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'twitch',
        name: 'Twitch',
        url: 'https://www.twitch.tv/arigeli_',
        label: 'Visitar perfil de Arigeli en Twitch',
        followers: '32.5k',
        image: {
          logo: Twitch,
          width: 200,
          height: 200,
        },
      },
    ],
    clips: [
      {
        text: 'Disfruta del titulo mientras puedas, por que este año es mio.',
        url: 'https://www.youtube.com/embed/qdS_XOZ5kyU?si=D8fgVfCSRy_SwZHv&amp;clip=UgkxEmtFin7L3_YLiJW_OyRkmeZtFj53PnkT&amp;clipt=EPWwAhj91wI',
      },
    ],
    workout: {
      videoID: 'rugHsv9JCSU',
      thumbnail: '/images/fighters/workoutThumbnails/arigeli-thumbnail.webp',
    },
  },
  {
    // https://www.biografia.de/tomas-mazza/
    id: 'tomas',
    name: 'Tomás',
    realName: 'Tomás Francisco Pérez Mazza',
    bio: 'El youtuber argentino Tomás Mazza, especializado en contenido sobre fitness y salud, vive su segunda preparación para subirse a un ring. Ya peleó el año pasado en el ‘Párense de manos 2’, otra gran velada de creadores que se disputa en Argentina y que tuvo también decenas de miles de espectadores en las gradas. Vivida ya la experiencia y conocido el sabor de la victoria, el reto para Mazza será aún mayor. Ahora espera que su gran crecimiento como creador vaya de la mano de un salto en el boxeo que le permita tumbar a Viruzz.',
    gender: 'masculino',
    birthDate: new Date(2000, 3, 16),
    height: 1.76,
    age: 25,
    weight: 80,
    country: 'ar',
    gallery: true,
    city: 'Buenos Aires',
    versus: 'viruzz',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/mazzatomas',
        label: 'Visitar perfil de Tomás en Instagram',
        followers: '2.9M',
        image: {
          logo: Instagram,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/@mazzatomas',
        label: 'Visitar perfil de Tomás en TikTok',
        followers: '2.5M',
        image: {
          logo: TikTok,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'youtube',
        name: 'Youtube',
        url: 'https://www.youtube.com/@tomasmazza',
        label: 'Visitar canal de Tomás en Youtube',
        followers: '855k',
        image: {
          logo: Youtube,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'x',
        name: 'X',
        url: 'https://x.com/MazzaTomas',
        label: 'Visitar perfil de Tomás en X',
        followers: '259.9k',
        image: {
          logo: X,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'twitch',
        name: 'Twitch',
        url: 'https://www.twitch.tv/mazzatomas',
        label: 'Visitar perfil de Tomás en Twitch',
        followers: '629k',
        image: {
          logo: Twitch,
          width: 200,
          height: 200,
        },
      },
    ],
    clips: [
      {
        text: 'Yo soy la cura del Viruzz.',
        url: 'https://www.youtube.com/embed/t7r5O_5B-E0?si=tmS6F4zyAwJ8hjfw&amp;clip=UgkxwZjrAtle4_JWz8SOQyqTYSle3QNZSPnD&amp;clipt=EKOm0wQYz_PTBA',
      },
      {
        text: 'Es un desafío muy grande la verdad nadie cree en mi ',
        url: 'https://www.youtube.com/embed/t7r5O_5B-E0?si=x1D7VSLOkHRznEbb&amp;clip=UgkxKSYyYGXEofS0Oaeh2MtubiTWnVTYUlks&amp;clipt=EIii2QQYoJfaBA',
      },
    ],
    workout: {
      videoID: 'FBjMQogPr-U',
      thumbnail: '/images/fighters/workoutThumbnails/tomas-thumbnail.webp',
    },
  },
  {
    // https://laletrade.com/biografias/youtuber/19752-carlos-belcast
    id: 'carlos',
    name: 'Carlos',
    bio: 'Referencia en su sector, Carlos Belcast es un creador de contenido especializado en fitness, entrenador personal y atleta de culturismo mexicano. Apasionado por contar su cambio gracias al deporte, su contenido no solo se centra en el plano físico, sino también en la mentalidad y actitud necesarias para alcanzar el siguiente nivel.',
    realName: 'Carlos Belcast',
    gender: 'masculino',
    birthDate: new Date(1998, 9, 5),
    height: 1.77,
    age: 26,
    weight: 85,
    gallery: true,
    country: 'mx',
    city: 'Monterrey, Nuevo León',
    versus: 'andoni',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/carlosbelcast/',
        label: 'Visitar perfil de Carlos en Instagram',
        followers: '5.1M',
        image: {
          logo: Instagram,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/@carlosbelcast',
        label: 'Visitar perfil de Carlos en TikTok',
        followers: '6.5M',
        image: {
          logo: TikTok,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'youtube',
        name: 'Youtube',
        url: 'https://www.youtube.com/@carlosbelcast',
        label: 'Visitar canal de Carlos en Youtube',
        followers: '1.42M',
        image: {
          logo: Youtube,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'x',
        name: 'X',
        url: 'https://x.com/CarlosBelcast',
        label: 'Visitar perfil de Carlos en X',
        followers: '22.1k',
        image: {
          logo: X,
          width: 200,
          height: 200,
        },
      },
      {
        id: 'twitch',
        name: 'Twitch',
        url: 'https://www.twitch.tv/carlosbelcastt',
        label: 'Visitar perfil de Carlos en Twitch',
        followers: '50.3k',
        image: {
          logo: Twitch,
          width: 200,
          height: 200,
        },
      },
    ],
    workout: {
      videoID: 'R3nXNgSLnYA',
      thumbnail: '/images/fighters/workoutThumbnails/carlos-thumbnail.webp',
    },
    clips: [
      {
        text: 'Estoy de acuerdo, es una máquina, y eso hace más emocionante para mí la pelea. Una pelea difícil, un reto para mí.',
        url: 'https://www.youtube.com/embed/NbaFxQiuFek?si=_zo9rym4J9nuprTz&amp;clip=UgkxA55s3XmbPCzb0W3fcV3a5ynwEsfrpWnY&amp;clipt=EMD-DBjIpQ0',
      },
      {
        text: 'Quiero poner a mi país en alto, es lo que más quiero.',
        url: 'https://www.youtube.com/embed/NbaFxQiuFek?si=ycZse19c6kilirh5&amp;clip=Ugkx_DVmBQCwGsesR_3YKdmsSI2VEzymSdZW&amp;clipt=EMWoDRjH1w0',
      },
      {
        text: 'Somos muy grandes amigos, nos queremos mucho… pero eso no quiere decir que nos vayamos a dar con todo.',
        url: 'https://www.youtube.com/embed/NbaFxQiuFek?si=1KpotzlUDqM1VYYQ&amp;clip=UgkxQadrp40FBpmDXn2yaSgdQJVUYUFaAqKO&amp;clipt=EOTJIhjL_CI',
      },
    ],
  },
] as const
