import type { Fighters } from '@/types/fighters'
import X from '@/assets/svg/x.svg'
import Instagram from '@/assets/svg/instagram.svg'
import Youtube from '@/assets/svg/youtube.svg'
import TikTok from '@/assets/svg/tiktok.svg'
import Twitch from '@/assets/svg/twitch.svg'

export const FIGHTERS: Fighters[] = [
  {
    id: 'edu-aguirre',
    name: 'Edu Aguirre',
    realName: 'Eduardo Aguirre',
    gender: 'masculino',
    birthDate: new Date(1988, 0, 14),
    height: 0,
    age: 38,
    weight: 0,
    country: 'es',
    versus: 'gaston-edul',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/eduaguirre7',
        label: 'Visitar perfil de Edu Aguirre en Instagram',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'x',
        name: 'X',
        url: 'https://x.com/EduAguirre7',
        label: 'Visitar perfil de Edu Aguirre en X',
        image: { logo: X, width: 200, height: 200 },
      },
    ],
    clips: [],
    bio: 'Periodista deportivo español, rostro habitual de El Chiringuito de Jugones y amigo íntimo de Cristiano Ronaldo. Su carácter y pasión en los debates televisivos lo han convertido en una de las figuras más reconocidas del periodismo deportivo en España.',
  },
  {
    id: 'gaston-edul',
    name: 'Gastón Edul',
    realName: 'Gastón Edul',
    gender: 'masculino',
    birthDate: new Date(1995, 11, 31),
    height: 0,
    age: 30,
    weight: 0,
    country: 'ar',
    versus: 'edu-aguirre',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/gastonedul',
        label: 'Visitar perfil de Gastón Edul en Instagram',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'x',
        name: 'X',
        url: 'https://x.com/gastonedul',
        label: 'Visitar perfil de Gastón Edul en X',
        image: { logo: X, width: 200, height: 200 },
      },
    ],
    clips: [],
    bio: 'Periodista deportivo argentino de ESPN y TyC Sports, conocido por cubrir a la selección argentina. Su estilo cercano y apasionado lo ha convertido en referente del periodismo deportivo en Latinoamérica.',
  },
  {
    id: 'fabiana-sevillano',
    name: 'Fabiana Sevillano',
    realName: 'Fabiana Sevillano',
    gender: 'femenino',
    birthDate: new Date(2002, 7, 8),
    height: 0,
    age: 23,
    weight: 0,
    country: 'es',
    city: 'Sevilla',
    versus: 'la-parce',
    socials: [
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/@fabiana.sevillano',
        label: 'Visitar perfil de Fabiana Sevillano en TikTok',
        followers: '1.9M',
        image: { logo: TikTok, width: 200, height: 200 },
      },
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/fabiana.sevillano',
        label: 'Visitar perfil de Fabiana Sevillano en Instagram',
        image: { logo: Instagram, width: 200, height: 200 },
      },
    ],
    clips: [],
    bio: 'Tiktoker sevillana con casi 2 millones de seguidores. Combatirá como local en el Estadio de La Cartuja, su ciudad natal. Su energía y desparpajo la hacen una de las favoritas del público.',
  },
  {
    id: 'la-parce',
    name: 'La Parce',
    realName: 'Valeria',
    gender: 'femenino',
    birthDate: new Date(1998, 0, 1),
    height: 0,
    age: 28,
    weight: 0,
    country: 'co',
    versus: 'fabiana-sevillano',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/_laparce_',
        label: 'Visitar perfil de La Parce en Instagram',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'twitch',
        name: 'Twitch',
        url: 'https://www.twitch.tv/laparce',
        label: 'Visitar perfil de La Parce en Twitch',
        image: { logo: Twitch, width: 200, height: 200 },
      },
      {
        id: 'x',
        name: 'X',
        url: 'https://x.com/_laparce_',
        label: 'Visitar perfil de La Parce en X',
        image: { logo: X, width: 200, height: 200 },
      },
    ],
    clips: [],
    bio: 'Streamer colombiana y presidenta de las Atlético Parceras en la Queens League. Conocida por su carácter fuerte y su comunidad fiel en Twitch.',
  },
  {
    id: 'clersss',
    name: 'Clersss',
    realName: 'Clara Merino',
    gender: 'femenino',
    birthDate: new Date(2001, 8, 15),
    height: 0,
    age: 24,
    weight: 0,
    country: 'es',
    versus: 'natalia-mx',
    socials: [
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/@clersssss',
        label: 'Visitar perfil de Clersss en TikTok',
        followers: '1.2M',
        image: { logo: TikTok, width: 200, height: 200 },
      },
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/clersss',
        label: 'Visitar perfil de Clersss en Instagram',
        image: { logo: Instagram, width: 200, height: 200 },
      },
    ],
    clips: [],
    bio: 'Tiktoker y creadora de contenido lifestyle española. Presidenta en la Queens League. Su naturalidad y cercanía con su audiencia la han convertido en una de las creadoras más queridas de su generación.',
  },
  {
    id: 'natalia-mx',
    name: 'Natalia MX',
    realName: 'Natalia García',
    gender: 'femenino',
    birthDate: new Date(1998, 0, 1),
    height: 0,
    age: 28,
    weight: 0,
    country: 'mx',
    versus: 'clersss',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/_nataliamx',
        label: 'Visitar perfil de Natalia MX en Instagram',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'twitch',
        name: 'Twitch',
        url: 'https://www.twitch.tv/nataliamx',
        label: 'Visitar perfil de Natalia MX en Twitch',
        image: { logo: Twitch, width: 200, height: 200 },
      },
      {
        id: 'x',
        name: 'X',
        url: 'https://x.com/_nataliamx19',
        label: 'Visitar perfil de Natalia MX en X',
        image: { logo: X, width: 200, height: 200 },
      },
    ],
    clips: [],
    bio: 'Streamer mexicana con una comunidad sólida en Twitch. Su carisma y estilo directo la han posicionado como una de las creadoras más relevantes de Latinoamérica.',
  },
  {
    id: 'kidd-keo',
    name: 'Kidd Keo',
    realName: 'Padua Keoma Salas Sánchez',
    gender: 'masculino',
    birthDate: new Date(1995, 8, 26),
    height: 0,
    age: 30,
    weight: 0,
    country: 'es',
    city: 'Alicante',
    versus: 'lit-killah',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/kiddkeo',
        label: 'Visitar perfil de Kidd Keo en Instagram',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'x',
        name: 'X',
        url: 'https://x.com/KiddKeo',
        label: 'Visitar perfil de Kidd Keo en X',
        image: { logo: X, width: 200, height: 200 },
      },
      {
        id: 'youtube',
        name: 'Youtube',
        url: 'https://www.youtube.com/@KiddKeo',
        label: 'Visitar canal de Kidd Keo en Youtube',
        image: { logo: Youtube, width: 200, height: 200 },
      },
    ],
    clips: [],
    bio: 'Rapero alicantino que revolucionó el trap en España. Pionero del género urbano en español, su música ha trascendido fronteras. Protagoniza el primer combate entre músicos en la historia de La Velada.',
  },
  {
    id: 'lit-killah',
    name: 'Lit Killah',
    realName: 'Mauro Román Monzón',
    gender: 'masculino',
    birthDate: new Date(1999, 9, 4),
    height: 0,
    age: 26,
    weight: 0,
    country: 'ar',
    versus: 'kidd-keo',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/litkillah',
        label: 'Visitar perfil de Lit Killah en Instagram',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'x',
        name: 'X',
        url: 'https://x.com/LitKillah',
        label: 'Visitar perfil de Lit Killah en X',
        image: { logo: X, width: 200, height: 200 },
      },
      {
        id: 'youtube',
        name: 'Youtube',
        url: 'https://www.youtube.com/@LitKillah',
        label: 'Visitar canal de Lit Killah en Youtube',
        image: { logo: Youtube, width: 200, height: 200 },
      },
    ],
    clips: [],
    bio: 'Rapero, cantante y streamer argentino. Una de las figuras más importantes del género urbano latinoamericano. Se ha comprometido a perder peso para el combate y quiere pelear sin casco.',
  },
  {
    id: 'alondrissa',
    name: 'Alondrissa',
    realName: 'Alondra Michelle',
    gender: 'femenino',
    birthDate: new Date(2001, 9, 30),
    height: 0,
    age: 24,
    weight: 0,
    country: 'pr',
    versus: 'angie-velasco',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/alondraa.michellee',
        label: 'Visitar perfil de Alondrissa en Instagram',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'twitch',
        name: 'Twitch',
        url: 'https://www.twitch.tv/alondrissa',
        label: 'Visitar perfil de Alondrissa en Twitch',
        image: { logo: Twitch, width: 200, height: 200 },
      },
    ],
    clips: [],
    bio: 'Streamer y youtuber puertorriqueña. Protagoniza el primer combate en la historia de La Velada sin ningún participante español. Su energía y carisma la hacen una de las favoritas del público latino.',
  },
  {
    id: 'angie-velasco',
    name: 'Angie Velasco',
    realName: 'Angelina Rocío Velasco',
    gender: 'femenino',
    birthDate: new Date(1998, 9, 30),
    height: 0,
    age: 27,
    weight: 0,
    country: 'ar',
    city: 'Rosario',
    versus: 'alondrissa',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/angieevelasco',
        label: 'Visitar perfil de Angie Velasco en Instagram',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'youtube',
        name: 'Youtube',
        url: 'https://www.youtube.com/@AngieVelasco',
        label: 'Visitar canal de Angie Velasco en Youtube',
        image: { logo: Youtube, width: 200, height: 200 },
      },
    ],
    clips: [],
    bio: 'Youtuber argentina de Rosario. Su estilo directo y sin filtros la ha convertido en una de las creadoras más populares de Argentina.',
  },
  {
    id: 'viruzz',
    name: 'Viruzz',
    realName: 'Víctor Mélida Cambra',
    gender: 'masculino',
    birthDate: new Date(1992, 4, 1),
    height: 1.85,
    age: 33,
    weight: 0,
    country: 'es',
    city: 'Zaragoza',
    versus: 'gero-arias',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/victormelida',
        label: 'Visitar perfil de Viruzz en Instagram',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'x',
        name: 'X',
        url: 'https://x.com/byViruZz',
        label: 'Visitar perfil de Viruzz en X',
        image: { logo: X, width: 200, height: 200 },
      },
      {
        id: 'youtube',
        name: 'Youtube',
        url: 'https://www.youtube.com/@ByViruZz',
        label: 'Visitar canal de Viruzz en Youtube',
        followers: '6M',
        image: { logo: Youtube, width: 200, height: 200 },
      },
    ],
    clips: [],
    bio: 'Youtuber español con más de 6 millones de suscriptores. El veterano absoluto de La Velada: esta es su quinta participación. Conocido por su nivel boxístico real, este combate sin casco y a 6 rounds será el de mayor nivel deportivo de la noche.',
  },
  {
    id: 'gero-arias',
    name: 'Gero Arias',
    realName: 'Gerónimo Arias',
    gender: 'masculino',
    birthDate: new Date(2005, 0, 1),
    height: 0,
    age: 21,
    weight: 0,
    country: 'ar',
    city: 'San Luis',
    versus: 'viruzz',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/geroooo_arias',
        label: 'Visitar perfil de Gero Arias en Instagram',
        image: { logo: Instagram, width: 200, height: 200 },
      },
    ],
    clips: [],
    bio: 'Joven influencer y boxeador argentino de San Luis. Ya demostró su nivel venciendo a Tomás Mazza en Párense de Manos 3. Llega a La Velada como la nueva generación que quiere destronar al veterano Viruzz.',
  },
  {
    id: 'samy-rivers',
    name: 'Samy Rivers',
    realName: 'Samantha Rivera Treviño',
    gender: 'femenino',
    birthDate: new Date(1998, 0, 1),
    height: 0,
    age: 28,
    weight: 0,
    country: 'mx',
    versus: 'roro',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/samyrivera',
        label: 'Visitar perfil de Samy Rivers en Instagram',
        image: { logo: Instagram, width: 200, height: 200 },
      },
    ],
    clips: [],
    bio: 'Streamer y youtuber mexicana. Vuelve a La Velada en busca de revancha contra Roro. Esta vez las condiciones son iguales para ambas.',
  },
  {
    id: 'roro',
    name: 'Roro',
    realName: 'Rocío López Bueno',
    gender: 'femenino',
    birthDate: new Date(1998, 0, 1),
    height: 0,
    age: 28,
    weight: 0,
    country: 'es',
    city: 'Madrid',
    versus: 'samy-rivers',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/roro.bueno',
        label: 'Visitar perfil de Roro en Instagram',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/@roro.bueno',
        label: 'Visitar perfil de Roro en TikTok',
        image: { logo: TikTok, width: 200, height: 200 },
      },
    ],
    clips: [],
    bio: 'Creadora de contenido madrileña conocida por su contenido de cocina y lifestyle. Vuelve a La Velada para enfrentarse de nuevo a Samy Rivers en una revancha muy esperada.',
  },
  {
    id: 'marta-diaz',
    name: 'Marta Díaz',
    realName: 'Marta Díaz García',
    gender: 'femenino',
    birthDate: new Date(2000, 9, 30),
    height: 0,
    age: 25,
    weight: 0,
    country: 'es',
    city: 'Sevilla',
    versus: 'tatiana-kaer',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/marta_diaz',
        label: 'Visitar perfil de Marta Díaz en Instagram',
        followers: '3.3M',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/@marta_diaz',
        label: 'Visitar perfil de Marta Díaz en TikTok',
        followers: '5.8M',
        image: { logo: TikTok, width: 200, height: 200 },
      },
    ],
    clips: [],
    bio: 'Influencer y modelo sevillana con millones de seguidores. Hermana de AlphaSniper97. Combatirá como local en La Cartuja en el que promete ser uno de los combates más mediáticos de la noche.',
  },
  {
    id: 'tatiana-kaer',
    name: 'Tatiana Kaer',
    realName: 'Tatiana Kaer',
    gender: 'femenino',
    birthDate: new Date(2004, 7, 28),
    height: 0,
    age: 21,
    weight: 0,
    country: 'es',
    city: 'Valencia',
    versus: 'marta-diaz',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/tatianakaer',
        label: 'Visitar perfil de Tatiana Kaer en Instagram',
        followers: '5M',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/@tatianakaer',
        label: 'Visitar perfil de Tatiana Kaer en TikTok',
        image: { logo: TikTok, width: 200, height: 200 },
      },
    ],
    clips: [],
    bio: 'Influencer y modelo valenciana de padre español y madre estonia. Novia de Héctor Fort, jugador del FC Barcelona. Con 5 millones de seguidores en Instagram, es una de las figuras más seguidas de su generación.',
  },
  {
    id: 'yosoyplex',
    name: 'YoSoyPlex',
    realName: 'Daniel Alonso',
    gender: 'masculino',
    birthDate: new Date(1997, 0, 1),
    height: 0,
    age: 29,
    weight: 0,
    country: 'es',
    versus: 'fernanfloo',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/yosoyplex',
        label: 'Visitar perfil de YoSoyPlex en Instagram',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'youtube',
        name: 'Youtube',
        url: 'https://www.youtube.com/@YoSoyPlex',
        label: 'Visitar canal de YoSoyPlex en Youtube',
        followers: '14M',
        image: { logo: Youtube, width: 200, height: 200 },
      },
    ],
    clips: [],
    bio: 'Youtuber español con 14 millones de suscriptores. Su contenido de humor y gaming lo ha convertido en uno de los creadores más populares de habla hispana.',
  },
  {
    id: 'fernanfloo',
    name: 'Fernanfloo',
    realName: 'Luis Fernando Flores Alvarado',
    gender: 'masculino',
    birthDate: new Date(1993, 6, 7),
    height: 0,
    age: 32,
    weight: 0,
    country: 'sv',
    versus: 'yosoyplex',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/fernanfloo',
        label: 'Visitar perfil de Fernanfloo en Instagram',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'youtube',
        name: 'Youtube',
        url: 'https://www.youtube.com/@Fernanfloo',
        label: 'Visitar canal de Fernanfloo en Youtube',
        followers: '50M',
        image: { logo: Youtube, width: 200, height: 200 },
      },
      {
        id: 'x',
        name: 'X',
        url: 'https://x.com/Fernanfloo',
        label: 'Visitar perfil de Fernanfloo en X',
        image: { logo: X, width: 200, height: 200 },
      },
    ],
    clips: [],
    bio: 'Leyenda de YouTube salvadoreño con 50 millones de suscriptores, uno de los creadores de habla hispana más grandes de la historia. Su participación en La Velada es uno de los momentos más esperados del evento.',
  },
  {
    id: 'grefg',
    name: 'Grefg',
    realName: 'David Cánovas Martínez',
    gender: 'masculino',
    birthDate: new Date(1997, 3, 24),
    height: 1.70,
    age: 29,
    weight: 67,
    country: 'es',
    city: 'Murcia',
    versus: 'illojuan',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/thegrefg',
        label: 'Visitar perfil de TheGrefg en Instagram',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'youtube',
        name: 'Youtube',
        url: 'https://www.youtube.com/@TheGrefg',
        label: 'Visitar canal de TheGrefg en Youtube',
        followers: '19.6M',
        image: { logo: Youtube, width: 200, height: 200 },
      },
      {
        id: 'twitch',
        name: 'Twitch',
        url: 'https://www.twitch.tv/thegrefg',
        label: 'Visitar perfil de TheGrefg en Twitch',
        followers: '12.3M',
        image: { logo: Twitch, width: 200, height: 200 },
      },
      {
        id: 'x',
        name: 'X',
        url: 'https://x.com/TheGrefg',
        label: 'Visitar perfil de TheGrefg en X',
        image: { logo: X, width: 200, height: 200 },
      },
    ],
    clips: [],
    bio: 'Youtuber y streamer murciano con casi 20 millones de suscriptores en YouTube y 12 millones en Twitch. Vigente campeón tras vencer a Westcol en La Velada V. Defiende su título en el evento principal a 6 rounds, sin casco y con peso pactado en 67 kg.',
  },
  {
    id: 'illojuan',
    name: 'IlloJuan',
    realName: 'Juan Alberto García Gámez',
    gender: 'masculino',
    birthDate: new Date(1994, 5, 22),
    height: 0,
    age: 32,
    weight: 67,
    country: 'es',
    city: 'Fuengirola, Málaga',
    versus: 'grefg',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/illojuan',
        label: 'Visitar perfil de IlloJuan en Instagram',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'twitch',
        name: 'Twitch',
        url: 'https://www.twitch.tv/illojuan',
        label: 'Visitar perfil de IlloJuan en Twitch',
        image: { logo: Twitch, width: 200, height: 200 },
      },
      {
        id: 'x',
        name: 'X',
        url: 'https://x.com/IlloJuan',
        label: 'Visitar perfil de IlloJuan en X',
        image: { logo: X, width: 200, height: 200 },
      },
    ],
    clips: [],
    bio: 'Streamer malagueño y una de las figuras más queridas de Twitch España. Debuta en La Velada con todo por demostrar contra el vigente campeón TheGrefg. Combate principal a 6 rounds, sin casco, guantes olímpicos y peso pactado en 67 kg.',
  },
]
